name: "Sub-issue"
description: "Subtarea de una issue"
title: "[DSI-] "
body:
  - type: textarea
    id: description
    attributes:
      label: "Descripción"
    validations:
      required: false

  - type: textarea
    id: done-criteria
    attributes:
      label: "Definición de hecho"
      placeholder: |
        - [ ] Criterio 1
        - [ ] Criterio 2
    validations:
      required: false
